config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users 
  resources :users, only: [:index, :show]
  resources :posts, only: [:new, :create, :show] do
   resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user

  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :name, :images, presence: true

  has_many :images
  accepts_nested_attributes_for :images, allow_destroy: true

  belongs_to :user
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
  #def uniine(user)
  #  likes.find_by(user_id: user.id).destroy
  #end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.new(user_id: current_user.id, post_id: params[:post_id])
    @like.save
    @likes = Like.where(post_id: params[:post_id])
    get_post
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    @like.destroy
    @likes = Like.where(post_id: params[:post_id])
    get_post
  end

  def get_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.limit(5)
  end
  def show
    @post = Post.find(params[:id])
  end
  def new
    if user_signed_in?
    @post = Post.new
    @post.images.new
    else
      redirect_to new_user_session_path
    end
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit( :name, images_attributes: [:src]).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mofustagram
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/likes/_like.html.haml
- if user_signed_in?
  - if post.like_user(current_user) 
    .item-button-container__left__dislike
      =link_to post_like_path(post), method: "DELETE", remote: true do
        %i.fas.fa-heart
        %span いいね！
        %span 
        = post.likes_count
  - else
    .item-button-container__left__like
      =link_to post_likes_path(post), method: "POST", remote: true do
        %i.fas.fa-heart
        %span いいね！
        %span
          = post.likes_count
-else
  .item-button-container__left__like
    %i.fas.fa-heart
      %span いいね！
      %span 
        = post.likes_count

app/views/likes/create.js.haml
$(".item-button-container__left").html("#{escape_javascript(render partial: 'like', locals: { post: @post, posts: @posts, likes: @likes, like: @like})}")

app/views/likes/destroy.js.haml
$(".item-button-container__left").html("#{escape_javascript(render partial: 'like', locals: { post: @post, posts: @posts, likes: @likes, like: @like})}")

app/views/posts/_form.html.haml
.contents
  .form__body
    = form_with model: @post ,local: true do |f|
      %h2
        投稿する
      .form__image
        .form__image__icon
          %label
            = icon('fas', 'camera')
            .input__image
              = f.fields_for :images do |i|
                = i.file_field :src
      %label 画像名
      .form__name
        = f.text_field :name
      .buttons
        = f.submit "投稿する",class:"buttons__send"
        =link_to root_path do
          .buttons__back もどる

app/views/posts/index.html.haml
.wrapper
  = render partial: 'shared/header'
  .new-post-button
    = link_to "投稿する",new_post_path
  .body
    .posts
      .post
        .image_box
          - @posts.each do |post|
            .post-list
              = link_to post_path(post) do
                .post_image
                  = image_tag post.images.first.src.url
                .name
                  = post.name.to_s
                
              
                

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
.post-detail
  .post-image
    = image_tag @post.images[0].src.to_s
  .post_name
    = @post.name
  .item-button-container
    .item-button-container__left
      = render partial: 'likes/like', locals: { post: @post, posts: @posts, likes: @likes, like: @like}

app/views/shared/_header.html.haml
.header
  .header-inner
    .innner-top
      .innner-top__box
        %form{"accept-charset": "UTF-8", action: "#", method: "get"}
          %input{name: "utf8", type: "hidden", value: "✓"}/
          %input{class:'innner-top__box-input', name: "key", placeholder: "キーワードから探す" }/
          %button{type: "submit"}
            %span.innner-top__box__icon
              = image_tag asset_path('icon-search 1.png'), type: '', alt: ''
      %ul.lists-right
        %li.lists-right__item
          -if user_signed_in?
            //= link_to mypage_index_path, class:"lists-right__item-mypage" do
            //  マイページ
            = link_to destroy_user_session_path, class:"lists-right__item-destroy", method: :delete do
              ログアウト
          -else   
            = link_to new_user_session_path, class:"lists-right__item-login" do
              ログイン
            = link_to new_user_registration_path, class:"lists-right__item-register" do
              新規会員登録